### ISSUE TITLE
递归有点问题，大哥能优化下吗

### ISSUE THREAD

**Issue by zhaozhanzhan** [HandsomeBrother/tiny-img-cli#3]
![image](https://user-images.githubusercontent.com/25058515/110444334-dabc8f00-80f7-11eb-8511-5270d0148a89.png)
上面那个写法好像无法递归遍历子目录

**Comment by zhaozhanzhan** [comment]
弄好了，不知道是不是因为node版本问题导致实例化传参未拿到
![image](https://user-images.githubusercontent.com/25058515/110453914-a9e15780-8101-11eb-8785-ff464ae82eb4.png)
![image](https://user-images.githubusercontent.com/25058515/110453998-bcf42780-8101-11eb-9f9d-8e166b779f8e.png)
![image](https://user-images.githubusercontent.com/25058515/110454063-ca111680-8101-11eb-9f9c-32d40010a23b.png)

**Comment by HandsomeBrother** [comment]
program使用问题，已解
